const std = @import("std");
const bio = @import("../root.zig");

const magic = "Generated by Image Lab";

const Header = struct {
    width: u32,
    height: u32,
    size_c: u16,
    pixel_type: bio.PixelType,
    little_endian: bool,
    pixel_offset: usize,
    pixel_len: usize,
};

pub fn matches(data: []const u8) bool {
    if (data.len < 64) return false;
    return std.mem.indexOf(u8, data[0..64], magic) != null;
}

pub fn readMetadata(data: []const u8) bio.ReaderError!bio.Metadata {
    const header = try parseHeader(data);
    return .{
        .format = "bioradscn",
        .width = header.width,
        .height = header.height,
        .size_c = header.size_c,
        .samples_per_pixel = header.size_c,
        .pixel_type = header.pixel_type,
        .little_endian = header.little_endian,
    };
}

pub fn readPlane(allocator: std.mem.Allocator, data: []const u8) bio.ReaderError!bio.Plane {
    return readPlaneIndex(allocator, data, 0);
}

pub fn readPlaneIndex(allocator: std.mem.Allocator, data: []const u8, plane_index: u32) bio.ReaderError!bio.Plane {
    if (plane_index != 0) return error.InvalidPlaneIndex;
    const metadata = try readMetadata(data);
    const header = try parseHeader(data);
    const plane_len = try planeByteCount(metadata);
    if (header.pixel_len < plane_len) return error.TruncatedData;
    if (header.pixel_offset > data.len or data.len - header.pixel_offset < plane_len) return error.TruncatedData;
    const out = try allocator.alloc(u8, plane_len);
    @memcpy(out, data[header.pixel_offset..][0..plane_len]);
    return .{ .metadata = metadata, .data = out };
}

fn parseHeader(data: []const u8) bio.ReaderError!Header {
    if (!matches(data)) return error.InvalidFormat;
    var pos: usize = 0;
    var current_type: []const u8 = "";
    var current_len: ?usize = null;
    var xml: ?[]const u8 = null;
    var pixel_offset: ?usize = null;
    var pixel_len: ?usize = null;

    while (pos < data.len) {
        const line = readLine(data, &pos) orelse break;
        const trimmed = std.mem.trim(u8, line, " \t\r\n");
        if (std.mem.startsWith(u8, trimmed, "Content-Type")) {
            current_type = headerValue(trimmed);
            if (std.mem.indexOfScalar(u8, current_type, ';')) |semi| current_type = std.mem.trim(u8, current_type[0..semi], " \t");
        } else if (std.mem.startsWith(u8, trimmed, "Content-Length")) {
            current_len = std.fmt.parseInt(usize, headerValue(trimmed), 10) catch return error.InvalidFormat;
        } else if (trimmed.len == 0 and current_len != null) {
            const len = current_len.?;
            if (pos > data.len or data.len - pos < len) return error.TruncatedData;
            if (std.mem.eql(u8, current_type, "text/xml")) {
                xml = data[pos..][0..len];
            } else if (std.mem.eql(u8, current_type, "application/octet-stream")) {
                pixel_offset = pos;
                pixel_len = len;
            }
            pos += len;
            current_len = null;
        }
    }

    const block = xml orelse return error.InvalidFormat;
    const width = parseU32Attr(block, "size_pix", "width") orelse return error.InvalidFormat;
    const height = parseU32Attr(block, "size_pix", "height") orelse return error.InvalidFormat;
    if (width == 0 or height == 0) return error.InvalidFormat;
    const size_c = parseU16Element(block, "channel_count") orelse 1;
    if (size_c == 0) return error.InvalidFormat;
    const max_value = parseU32Attr(block, "scanner", "max_value") orelse return error.InvalidFormat;
    const pixel_type: bio.PixelType = if (max_value <= 256) .uint8 else if (max_value <= 65535) .uint16 else return error.UnsupportedVariant;
    const little_endian = if (parseTextElement(block, "endian")) |endian| std.mem.eql(u8, std.mem.trim(u8, endian, " \t\r\n"), "little") else false;

    return .{
        .width = width,
        .height = height,
        .size_c = size_c,
        .pixel_type = pixel_type,
        .little_endian = little_endian,
        .pixel_offset = pixel_offset orelse return error.InvalidFormat,
        .pixel_len = pixel_len orelse return error.InvalidFormat,
    };
}

fn readLine(data: []const u8, pos: *usize) ?[]const u8 {
    if (pos.* >= data.len) return null;
    const start = pos.*;
    while (pos.* < data.len and data[pos.*] != '\n' and data[pos.*] != '\r') : (pos.* += 1) {}
    const end = pos.*;
    if (pos.* < data.len and data[pos.*] == '\r') pos.* += 1;
    if (pos.* < data.len and data[pos.*] == '\n') pos.* += 1;
    return data[start..end];
}

fn headerValue(line: []const u8) []const u8 {
    if (std.mem.indexOfScalar(u8, line, ':')) |colon| return std.mem.trim(u8, line[colon + 1 ..], " \t");
    if (std.mem.indexOfScalar(u8, line, ' ')) |space| return std.mem.trim(u8, line[space + 1 ..], " \t");
    return "";
}

fn parseU32Attr(xml: []const u8, element: []const u8, attr: []const u8) ?u32 {
    const value = parseAttr(xml, element, attr) orelse return null;
    return std.fmt.parseInt(u32, value, 10) catch null;
}

fn parseU16Element(xml: []const u8, element: []const u8) ?u16 {
    const text = parseTextElement(xml, element) orelse return null;
    return std.fmt.parseInt(u16, std.mem.trim(u8, text, " \t\r\n"), 10) catch null;
}

fn parseAttr(xml: []const u8, element: []const u8, attr: []const u8) ?[]const u8 {
    const tag = findStartTag(xml, element) orelse return null;
    const attr_pos = std.mem.indexOf(u8, tag, attr) orelse return null;
    var i = attr_pos + attr.len;
    while (i < tag.len and std.ascii.isWhitespace(tag[i])) : (i += 1) {}
    if (i >= tag.len or tag[i] != '=') return null;
    i += 1;
    while (i < tag.len and std.ascii.isWhitespace(tag[i])) : (i += 1) {}
    if (i >= tag.len or (tag[i] != '"' and tag[i] != '\'')) return null;
    const quote = tag[i];
    i += 1;
    const start = i;
    while (i < tag.len and tag[i] != quote) : (i += 1) {}
    if (i >= tag.len) return null;
    return tag[start..i];
}

fn parseTextElement(xml: []const u8, element: []const u8) ?[]const u8 {
    const tag_start = findStartTagOffset(xml, element) orelse return null;
    const tag_end = std.mem.indexOfScalarPos(u8, xml, tag_start, '>') orelse return null;
    const text_start = tag_end + 1;
    var end_tag_buf: [64]u8 = undefined;
    if (element.len + 3 > end_tag_buf.len) return null;
    end_tag_buf[0] = '<';
    end_tag_buf[1] = '/';
    @memcpy(end_tag_buf[2..][0..element.len], element);
    end_tag_buf[2 + element.len] = '>';
    const end_tag = end_tag_buf[0 .. element.len + 3];
    const text_end_rel = std.mem.indexOf(u8, xml[text_start..], end_tag) orelse return null;
    return xml[text_start..][0..text_end_rel];
}

fn findStartTag(xml: []const u8, element: []const u8) ?[]const u8 {
    const start = findStartTagOffset(xml, element) orelse return null;
    const end = std.mem.indexOfScalarPos(u8, xml, start, '>') orelse return null;
    return xml[start..end];
}

fn findStartTagOffset(xml: []const u8, element: []const u8) ?usize {
    var needle_buf: [64]u8 = undefined;
    if (element.len + 1 > needle_buf.len) return null;
    needle_buf[0] = '<';
    @memcpy(needle_buf[1..][0..element.len], element);
    const needle = needle_buf[0 .. element.len + 1];
    return std.mem.indexOf(u8, xml, needle);
}

fn planeByteCount(metadata: bio.Metadata) bio.ReaderError!usize {
    const row = std.math.mul(usize, metadata.width, metadata.bytesPerPixel()) catch return error.UnsupportedVariant;
    return std.math.mul(usize, row, metadata.height) catch return error.UnsupportedVariant;
}

test "reads biorad scn raw block" {
    const xml =
        "<root><size_pix width=\"2\" height=\"1\"/><scanner max_value=\"255\"/><channel_count>1</channel_count><endian>little</endian></root>";
    const prefix = "Generated by Image Lab\r\n";
    const headers =
        "Content-Type: text/xml\r\n" ++
        "Content-Length: " ++ "126" ++ "\r\n\r\n";
    try std.testing.expectEqual(@as(usize, 126), xml.len);
    const pixels_header =
        "\r\nContent-Type: application/octet-stream\r\n" ++
        "Content-Length: 2\r\n\r\n";
    const data = prefix ++ headers ++ xml ++ pixels_header ++ [_]u8{ 5, 6 };

    try std.testing.expect(matches(data[0..]));
    const metadata = try readMetadata(data[0..]);
    try std.testing.expectEqualStrings("bioradscn", metadata.format);
    try std.testing.expectEqual(@as(u32, 2), metadata.width);
    try std.testing.expectEqual(@as(u32, 1), metadata.height);

    const plane = try readPlane(std.testing.allocator, data[0..]);
    defer std.testing.allocator.free(plane.data);
    try std.testing.expectEqualSlices(u8, &.{ 5, 6 }, plane.data);
}
